### PR TITLE
Feature delete review

### PR DESCRIPTION
**Pull request by bagashvilit**
test PR

### CODE REVIEW

**Review by bagashvilit — COMMENTED** [review]
test review

**Review by johnsc1 — CHANGES_REQUESTED** [review]
Test request changes

**Comment by dluman** [comment]
I am reviewing this work. 5 stars. Would `commit` again.

**Review by dluman — COMMENTED** [review]
This work is the best work I've ever seen.

**Review by dluman — CHANGES_REQUESTED** [review]
Oh no! I think I found a change!

**Pull request closed without merging**
